# Generated by Django 4.2.5 on 2023-09-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.JSONField()),
                ('access_time', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=255)),
                ('user_identity', models.CharField(blank=True, max_length=255, null=True)),
                ('stable_fp', models.CharField(db_index=True, max_length=255)),
                ('loose_fp', models.CharField(max_length=255)),
            ],
        ),
    ]
