# Generated by Django 4.2.5 on 2023-09-13 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('browserintel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprintdata',
            name='user_identity',
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='bot_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='browser',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='browser_private_mode',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='device',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='headless_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='is_bot',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='lies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='resistance',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='stealth_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='timezone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintdata',
            name='user_identifier',
            field=models.CharField(default='anonymous', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fingerprintdata',
            name='access_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fingerprintdata',
            name='stable_fp',
            field=models.CharField(max_length=255),
        ),
    ]
