# Generated by Django 4.2.5 on 2023-10-11 21:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('browserintel', '0002_remove_fingerprintdata_user_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintdata',
            name='request_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, null=True),
        ),
    ]
