# Generated by Django 4.2.8 on 2024-01-24 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ENT', 'entity'), ('OBJ', 'object')], max_length=50)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('metadata', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processor_type', models.CharField(max_length=50)),
                ('artifact_type', models.CharField(choices=[('RAW', 'raw'), ('OBSRV', 'observation')], max_length=50)),
                ('data', models.JSONField()),
                ('metadata', models.JSONField()),
                ('pipeline_run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capabilities.pipelinerun')),
            ],
        ),
    ]
