# Generated by Django 4.2.8 on 2024-01-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0002_alter_pipelinerun_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='pipeline_run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capabilities.pipelinerun'),
        ),
    ]
