# Generated by Django 4.2.8 on 2024-01-26 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0003_alter_artifact_pipeline_run_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='hash',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='capabilities.entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='artifact_type',
            field=models.CharField(choices=[('RAW', 'raw'), ('SIG', 'signal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='entity',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[('audio_wav', 'audio_wav'), ('json', 'json')], max_length=50),
        ),
    ]
