# Generated by Django 4.2.8 on 2024-01-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
