# Generated by Django 4.2.8 on 2024-01-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0004_entity_created_ts_entity_hash_entity_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
